### ISSUE TITLE
Feature request : extract section of page directly using URL

### ISSUE THREAD

**Issue by cjohnsonuk** [splitbrain/dokuwiki-plugin-upgrade#108]
Summary
I can pull the whole page content by appending &do=export_xhtml and &do=export_xhtmlbody.  I'd like to extract just the text under the named section

Detail
I have a system for managing manuals created using Dokuwiki.  I use the "include" plugin to pull the ====Content==== part of my topic pages into pages for each Chapter allowing the authors to reuse topics in chapters for different clients.  Each topic page includes support and other information under different headings.  I use "include" so this information does not show within the Chapters.

I'd like to extract the topic content text programmatically to include as the text in help "pop ups" on a web page.  I can pull the whole page content by appending &do=export_xhtml and &do=export_xhtmlbody but using the #pagesection syntax (that works with include) in the url doesn't work.  I tried looking at the xml but even the "wiki.getPageHTML" appears to pull the whole page, not just the section.

Is there a way to do an equivalent to "?do=export_xhtml&section=content&inline=1&noheader=1"? (ie the include syntax via the URL?)

Any suggestions as to how I can get round this appreciated...

**Comment by splitbrain** [comment]
wrong bug tracker
