### ISSUE TITLE
Pages not visible after update

### ISSUE THREAD

**Issue by Ma4x** [splitbrain/dokuwiki-plugin-upgrade#109]
Hello,

i upgrades with the upgrader-plugin from  2015-08-10a "Detritus" to  2016-06-26a "Elenor of Tsort".
After the upgrade there are no pages anywhere, besides the "stock" ones. There are still the changes in the stock pages.
The other pages are also not in the Sitemap.

On the server i find all the pages in the /data/pages/ path.

Anyone know some help?

Greetings Max

**Comment by splitbrain** [comment]
compatibility problems with DokuWiki should be reported in DokuWiki's bug tracker.
