### ISSUE TITLE
Old bundled plugins were not uninstalled

### ISSUE THREAD

**Issue by Harvie** [splitbrain/dokuwiki-plugin-upgrade#117]
Dokuwiki changed bundled plugin for managing plugins, but when i upgraded it the old plugin still remained installed along with the new. eg.:

OLD https://www.dokuwiki.org/plugin:plugin
NEW https://www.dokuwiki.org/plugin:extension

This is not only case. There were more of these, but this one was easiest to spot.

I think this should be somehow automatically detected and replaced.

**Comment by bug** [comment]
In deleted.files:

    # removed in 2014-05-05
    lib/plugins/plugin/admin.php
    lib/plugins/plugin/classes/ap_delete.class.php
    lib/plugins/plugin/classes/ap_download.class.php
    ...

and as written on the plugin:plugin page, the plugin was superseeded by the extension plugin in release Ponder Stibbons which is 2014-05-05. It **is** detected, but depending on your upgrade procedure the old files are deleted or not.

What other "more of these", do you see?

**Comment by Harvie** [comment]
What do you mean by "depending on your upgrade procedure" ?
I've been using this plugin to do the upgrade. There are no much choices to make. It's almost everything up to plugin.

**Comment by bug** [comment]
Which other files have you found left installed after the upgrade?
