### ISSUE TITLE
Plugin "Could not determine the newest version of DokuWiki."

### ISSUE THREAD

**Issue by grischahaag** [splitbrain/dokuwiki-plugin-upgrade#119]
"Wiki Upgrade" reports a warning:

> Could not determine the newest version of DokuWiki. Could not connect to ssl://raw.githubusercontent.com:443 (0)
> Could not determine the newest version of DokuWiki.
> ￼You're currently running DokuWiki Release 2017-02-19a "Frusterick Manners".
> ￼Errors above! You should not continue!

The corresponding log is:

> [Fri Mar 10 18:27:54 2017] [warn] [client xxx.xxx.xxx.xxx] mod_fcgid: stderr: PHP Strict Standards:  Only variables should be passed by reference in /xxx/lib/plugins/upgrade/admin.php on line 139, referer: https://xxx/doku.php?id=start&do=admin&page=upgrade

Continuing result in further errors:

> Downloading archive from https://github.com/splitbrain/dokuwiki/archive/stable.tar.gz...
> Could not connect to ssl://github.com:443 
> 

The plugin was functional before (and is still on an other host with other environment). The problem may be related to an PHP-upgrade to PHP Version 5.6.30 but my hoster and I have no idea how to solve this issue.

**Comment by grischahaag** [comment]
we could solve the problem:

there was a problem with the mentioned PHP-upgrade, SSL and a missing server.pem
http://php.net/manual/en/migration56.openssl.php

**Comment by grupodeca** [comment]
How do you solve the problem?

**Comment by therealx** [comment]
@grupodeca if you're on ubuntu, do the following as root:

```
sudo update-ca-certificates
cd /etc/ssl/certs
sudo wget http://curl.haxx.se/ca/cacert.pem --no-check-certificate
chmod 777 cacert.pem
```
