### ISSUE TITLE
Update fails to 2018-04-22 "Greebo"

### ISSUE THREAD

**Issue by MaRlik83** [splitbrain/dokuwiki-plugin-upgrade#137]
I'm running 2017-02-19e "Frusterick Manners" and try to update to the latest release. Everything seems to be okay, but some error occurs while the permission check:

> /install.php ist nicht beschreibbar!
/.htaccess.dist ist nicht beschreibbar!
Einige Dateien sind nicht beschreibbar. Die automatische Aktualisierung ist nicht möglich.

Both files doesn’t exist. I never had any problems running an update so far. Is this is a problem due to Greebo?

**Comment by splitbrain** [comment]
No it's a problem with your setup. Those files need to be writable. If they don't exist, permissions to create them need to be available.
