### ISSUE TITLE
Php error with Dokuwiki Release 2018-04-22 "Greebo"

### ISSUE THREAD

**Issue by claudiux** [splitbrain/dokuwiki-plugin-upgrade#138]
Hi,

There is a Php error when the upgrade plugin is enabled in Dokuwiki Release 2018-04-22 "Greebo".

`PHP Fatal error:  Cannot redeclare class HTTPClient in lib/plugins/upgrade/HTTPClient.php on line 29`

Consequence : the admin page (/?do=admin) can't be loaded; the page appears empty.

Disabling the upgrade plugin by a `$plugins['upgrade'] = 0;` line in the `conf/plugins.local.php` file solves (temporarily) the problem.

**Comment by mjbohn** [comment]
Hi
I just wanted to test the upgrade-plugin for the first time, to upgrade from "2017-02-19e "Frusterick Manners"" to Greebo.

Same error on "Frusterick Manners".

**Comment by splitbrain** [comment]
Should be fixed now. Please reinstall the upgrade plugin and try again

**Comment by claudiux** [comment]
Yesss ! It's working fine. Thank you @splitbrain !
