### ISSUE TITLE
Doesn't upgrade, despite success message

### ISSUE THREAD

**Issue by EttinCon** [splitbrain/dokuwiki-plugin-upgrade#139]
Wiki is not upgrading, even if I create the below folder and eliminate the warnings.
> Updating files...
>  All files updated.
> 
> **Warning: file(../wiki/data/tmp/dokuwiki-upgrade/data/deleted.files): failed to open stream: No such file or directory in /home/public/world/wiki/lib/plugins/upgrade/admin.php on line 416**
> 
> **Warning: Invalid argument supplied for foreach() in ../wiki/lib/plugins/upgrade/admin.php on line 417**
>  Upgrade completed. Enjoy your new DokuWiki

**Comment by splitbrain** [comment]
the deleted.files file should be part of the download. It seems the download didn't work for some reason (or the tgz is empty?) Maybe some kind of firewall interferred. No way to debug this, so I'm closing.
