### ISSUE TITLE
some PHP errors upgrading to latest release

### ISSUE THREAD

**Issue by bradbulger** [splitbrain/dokuwiki-plugin-upgrade#143]
> DEPRECATED: 'Non-static method admin_plugin_upgrade::_say() should not be called statically' in '/path/to/wiki/lib/plugins/upgrade/VerboseTarLib.class.php' line 173

and

> SYSTEM NOTICE: 'Only variables should be passed by reference' in '/path/to/wiki/lib/plugins/upgrade/admin.php' line 142

i saw issue #69 but it looked like that got dropped?

**Comment by bradbulger** [comment]
the changes i made to patch these - i can't upload a patch file i guess (?) so here's the gist link

https://gist.github.com/bradbulger/4bdf92adff912fbc8fe2b9c3df2d55f2

**Comment by splitbrain** [comment]
could you make this a proper pull request?

**Comment by bradbulger** [comment]
I downloaded the previous DokuWiki release, 2017-02-19f "Frusterick Manners", with the current release of the plugin, and ran the upgrade plugin through the web UI. I did not see any of these errors. I'm running php 7.0.33 now, though, and I may have been using php 7.1 or 7.2 when I last looked. I will be upgrading php in the near future, I'll check again.
