### ISSUE TITLE
Feature Request: Respect uninstalled plugins

### ISSUE THREAD

**Issue by fthommen** [splitbrain/dokuwiki-plugin-upgrade#165]
Whenever the upgrade plugin runs, it reinstalls all previously uninstalled "core" plugins, even the deprecated ones. I.e. after each update, one has to run a manual round of plugin cleanups. It would be great, if the upgrade process wouldn't reinstall those plugins (and also consider the installed languages (#55) ;-)

**Comment by splitbrain** [comment]
won't implement. I recommend disabling the plugins instead.
