### ISSUE TITLE
Upgrade to  2018-04-22b "Greebo"  - errors because of some not writeable files

### ISSUE THREAD

**Issue by martk70** [splitbrain/dokuwiki-plugin-upgrade#167]
Advise to abort installation after the VERIFICATION step: Errors above! You should not continue!
The errors are mainly in language files (which I don't even have, I looked through ftp. I only have te EN (english) folder). Apart from that the list is below (I left the language files out).

What I tried:
* My installation is pretty new (sept 2018). A suspicious plugin might be 'denyactions'?  I had that installed but removed it. Still not succesful.
* I reinstalled the upgrade plugin.
* I reset the file permissions through ftp. I tried 644. Not succesful.

Thank you for your work on Dokuwiki.
Kind regards, Martin

----

! /**doku.php** is not writable!
! /inc/lang/.htaccess is not writable!
! /inc/lang/af is not writable!
! /inc/lang/ar is not writable!
....
! /inc/lang/zh is not writable!
! /inc/lang/zh-tw is not writable!
! /inc/parser/**handler.php** is not writable!
! /inc/**search.php** is not writable!
! /**VERSION** is not writable!
! Some files aren't writable. Automatic upgrade not possible.

**Comment by splitbrain** [comment]
please see https://www.dokuwiki.org/install:permissions#file_permissions_a_short_reminder about how Unix permissions work. there is no simple answer to your question. it depends on the user your php process runs on and the owner of your files.
