### ISSUE TITLE
rc2-2020-06-01 - Could not determine the newest version of DokuWiki

### ISSUE THREAD

**Issue by gerardnico** [splitbrain/dokuwiki-plugin-upgrade#190]
Hallo,

For the short explanation, the plugin does not recognize the version
```
rc2-2020-06-01 "Hogfather" RC2
```
and shows the following message
```
Could not determine the newest version of DokuWiki.
```

This is because the pattern is not good.
I was on rc-2020-06-01 and I could still perform a successfull upgrade.

More information below on where the message comes from as I don't know what the version scheme is, I have not done any PR.

Cheers
Nico

The version 
https://raw.githubusercontent.com/splitbrain/dokuwiki/stable/VERSION
https://github.com/splitbrain/dokuwiki/commit/b83837fe1b7923c4241bae6e09ba68e38293ccce

```
rc2-2020-06-01 "Hogfather" RC2
```
is not recognized by the pattern
```
(^| )(?:rc)?(\d\d\d\d-\d\d-\d\d[a-z]*)( |$)
```
located at this line:

https://github.com/splitbrain/dokuwiki-plugin-upgrade/blob/master/admin.php#L244

And we get the error
```
Could not determine the newest version of DokuWiki.
```
a pattern that would work is this one
```
(^| )(?:rc\d-)?(\d\d\d\d-\d\d-\d\d[a-z]*)( |$)
```

**Comment by splitbrain** [comment]
Apparently it has been so long since we had RCs, that neither I nor @bug could remember the format we used to mark RCs. I believe we did it differently in the past, but oh well... I'll update the pattern.

**Comment by bug** [comment]
Damned, I'm sorry for that and confirm it's been ages we had not done several RCs so I messed up the naming

**Comment by bug** [comment]
(^| )(?:rc)?(\d\d\d\d-\d\d-\d\d[a-z]*)( |$)
where was the "2" of the second RC supposed to be again in that pattern?

**Comment by splitbrain** [comment]
I just looked in the git history. We had for example `'rc2013-11-18 "Binky RC2"'`. The date would update for each RC and the RC2 was only in the name.

**Comment by splitbrain** [comment]
should work now with the latest release of the plugin.
