### ISSUE TITLE
Donate link goes to an errornous page

### ISSUE THREAD

**Issue by DFF-fred** [splitbrain/dokuwiki-plugin-upgrade#191]
Hi! Was thinking to offer a coffee (mine at home is better, but it's probably too far and not the right time to visit). I clicked, got a SSL warning, and then the redirect on dokuwiki site went to a 404.
Probably not a life threatening issue, but still....

**Comment by splitbrain** [comment]
Thanks for letting me know. There was a problem with the SSL setup for the donate subdomain. It's fixed now.

**Comment by DFF-fred** [comment]
Enjoy your coffee then! :+1:

**Comment by splitbrain** [comment]
merci :coffee:
