### ISSUE TITLE
Update Plugin does not install config in DOKU_CONF folder...

### ISSUE THREAD

**Issue by jaguart** [splitbrain/dokuwiki-plugin-upgrade#198]
I found during the recent Hogfather upgrade, that if I have:

    # ./inc/preload.php
    # Config moved out of doc-root to enable simpler backup of Dokuwiki
    define('DOKU_CONF','/var/acme/dokuwiki/conf/');

The new ./conf/* files are not copied into the configured custom conf folder - which leaves the wiki running on new code with old config. It's also confusing to have two sets of conf.

I recommend that the Upgrade Plugin check this setting, and if it has been changed, that the upgraded conf folder contents should be at least also copied into the custom location.

This does leave copies in the default location - which is confusing for devops - I wasted several hours today trying to determine why some config was not being applied, before I discovered the ./inc/preload.php setting. Perhaps you could prompt and remove the files in the default location.

Note that this situation only exists because LOCAL config is written into the config directory and needs to be backed-up.

A full solution would be for DokuWiki to store ALL user changeable files in DATA - e.g. something like data/config_local/XXX.php - this would mean that we could just backup DATA and not bother with inc/preload.php custom settings... but I guess that's a different ticket.

**Comment by splitbrain** [comment]
please refer to https://www.dokuwiki.org/plugin:upgrade#q_a about the limitations of the upgrade plugin.
