### ISSUE TITLE
After upgrade  "currently unable to handle this request. HTTP ERROR 500"

### ISSUE THREAD

**Issue by AzureCloudMonk** [splitbrain/dokuwiki-plugin-upgrade#200]
Backed up three different sites, and did upgrades.  Each time on all 3 sites, including with the RC version (release candidate 3 2020-06-09 "Hogfather") and this new upgrade (2020-07-29 "Hogfather") immediately after it completes the upgrade "successfully", I get a "currently unable to handle this request. HTTP ERROR 500".  Then the Wiki is dead is the water. 

I revert to backup and I am back in business.  Any ideas?

**Comment by splitbrain** [comment]
Please see the hints in the DokuWiki changelog about plugin compatibility.
