### ISSUE TITLE
Plugin shows an available upgrade

### ISSUE THREAD

**Issue by prschopf** [splitbrain/dokuwiki-plugin-upgrade#201]
When I go to check for updates, it is showed:

![upgrade](https://user-images.githubusercontent.com/16743256/90933088-c91ece80-e3d5-11ea-9dee-847dd8eece99.jpg)

And I may click on "Continue" button. Is it right?

**Comment by mrazekpetr** [comment]
I have the same problem.

**Comment by itmuecke** [comment]
Same problem here.
Reinstalling doesn't change this behavior.
