### ISSUE TITLE
Update page just loads forever

### ISSUE THREAD

**Issue by sgtsilver** [splitbrain/dokuwiki-plugin-upgrade#208]
Hello there,

when I try to check for an Update the Page just stays blank and loads indefinitely - the "welcome page" of the Plugin is shown correctly. The DokuWiki I am running is running since some years now and this is the first time the upgrade plugin shows that behaviour. I've changed nothing since my install of Dokuwiki so I would assume that the ownership and all of that of the folders is correct. No plugin ever said anything regarding that, because I've done it with the help of the official authorization guide.

Is there anything I could supply? Logs?

**Comment by M-ax-G** [comment]
I am running Release 2020-07-29 "Hogfather", whihc I had updated with the upgrade plug-in at the time.
Today updated my plug-ins, including the upgrade plugin.
Then ran the upgrade plugin, which provides the same timeline graph as usual. when hitting continue, it clears the timeline and shows an empty sub-window. Not progressing further, ever. (checked hours and days later)
![image](https://user-images.githubusercontent.com/21173730/179340122-36fee893-9d11-463c-9dee-63ed3773d133.png)

**Comment by splitbrain** [comment]
See https://www.dokuwiki.org/faq:blankpage

**Comment by M-ax-G** [comment]
Thank you. Had a read... all I can see is access.log entries...
However, I let the thing run and got this:
`Could not determine the newest version of DokuWiki. Socket disconnected while writing request
! Could not determine the newest version of DokuWiki.
 You're currently running DokuWiki 2020-07-29 "Hogfather".
! New DokuWiki releases need at least PHP 7.2, but you're running 7.0.33-0+deb9u7. You should upgrade your PHP version before upgrading!`

A PHP upgrade is in order...
