### ISSUE TITLE
display problem

### ISSUE THREAD

**Issue by id027102** [splitbrain/dokuwiki-plugin-upgrade#212]
Installing upgrade on upgrade-plugin to day , and I have problem with display , you can see in attached images screenshot of browser when login : 
before : before plugin is upgraded
after : after plugin is upgraded
Needed to restore from backup , to get back ok.

![after](https://user-images.githubusercontent.com/45401482/125187177-9caeb380-e22e-11eb-9691-dd5ecad3d428.png)
![before](https://user-images.githubusercontent.com/45401482/125187186-a59f8500-e22e-11eb-8bf9-f0a3050add9f.png)

**Comment by id027102** [comment]
Images are inverset the first is after upgrade .

**Comment by splitbrain** [comment]
Your css isn't loaded correctly. Probably an incompability in one of your plugins or the template. This has nothing to do with the upgrade plugin. Try the forum to get help with trouble shooting.
