### ISSUE TITLE
"Igor" broke farm animals

### ISSUE THREAD

**Issue by phil-ide** [splitbrain/dokuwiki-plugin-upgrade#219]
I upgraded my wiki farm to "Igor" rc2022-06-26, and all my animals broke. The farmer ran fine.

I determined that the log folder created had the wrong owner and group (both root), changed them to www-data:

sudo chown www-data:www-data /var/www/data/log

and and my animal were accessible again. This may be a problem with the "upgrade" plugin rather than "Igor". This is probably not going to be an issue on Windows OS.

**Comment by splitbrain** [comment]
The upgrade plugin neither knows about nor touches the animals.
