### ISSUE TITLE
Shortcoming of upgrade plugin?

### ISSUE THREAD

**Issue by PEOM** [splitbrain/dokuwiki-plugin-upgrade#222]
When a new DokiWiki system is issued I get this kind of message:
New release available: 2022-07-31 "Igor". [upgrade now!](http://download.dokuwiki.org/) [52.2] [(what's this?)](http://www.dokuwiki.org/update_check)
When I click on "upgrade now," nothing changes on the screen. It looks like clicking did nothing. Is there some way you could make the link gray-out once it has set things in progress? (I'm a spoiled Mac user.)

**Comment by PEOM** [comment]
I have discovered that when opening via a Macintosh it does one thing, and that is to change the version name. Then there may be a flaw when making corrections to the Wiki. It will refuse to save them. 

Could you please check with somebody who knows what s/he is doing on a Mac and warn people f this turns out to be a problem? Thanks.

**Comment by PEOM** [comment]
I think I could create a new folder on iPage and then use the "Installation Remote." Then I could copy the relevant data files over from the old version.

**Comment by splitbrain** [comment]
Sorry, I have no idea what you are talking about. This issue contains no actionable info for me, so I will close this.
