### ISSUE TITLE
Installed plugin -> admin page empty

### ISSUE THREAD

**Issue by Longshot** [splitbrain/dokuwiki-plugin-upgrade#224]
Installed with the plugin manager it to easily upgrade but the admin page is empty after installation.
How do I remove the plugin?

**Comment by splitbrain** [comment]
https://www.dokuwiki.org/faq:blankpage

**Comment by Longshot** [comment]
It was just the admin page that didn't load.
Every other page loaded normally.

Everything worked again after removing this update plugin.
