### ISSUE TITLE
Upgrade plugin claims there is a newer version, but there isn't

### ISSUE THREAD

**Issue by fthommen** [splitbrain/dokuwiki-plugin-upgrade#225]
When upgrading, there is a note about a newer upgrade plugin:
![image](https://user-images.githubusercontent.com/279232/197036898-cc62dc1b-d492-472c-bf24-cab248ca6200.png)

but there isn't any:
![image](https://user-images.githubusercontent.com/279232/197036540-8d358666-ce72-4f3b-8999-fbb8a9e8ef9b.png)

and there is also no new release visible in GitHub:
![image](https://user-images.githubusercontent.com/279232/197036655-ae1e61be-a795-4948-8e36-c4f059358328.png)

**Comment by kroimon** [comment]
I ran into the same issue which prevents me from automatically updating DokuWiki.

I think the reason is that commit 70df1f6d4fb47adbfc2238f6a092834d62de983b increased the version number in master, but the corresponding tag has not been created.

**Comment by shaaati** [comment]
I think @kroimon is right. As a workaround you can "reinstall" the plugin from the extension management page instead of searching for the non-existent "update" button.

**Comment by fthommen** [comment]
Thanks @shaaati, reinstalling the plugin fixed the issue

**Comment by shaaati** [comment]
I don't think this issue should be closed because the root cause still exists and it affects all other users of this plugin. See @kroimon's post for the proper fix which needs to be implemented by the plugin author.
