### ISSUE TITLE
Can't update from 2022-07-31a "Igor" to 2023-04-04 "Jack Jackrum"

### ISSUE THREAD

**Issue by grockle1** [splitbrain/dokuwiki-plugin-upgrade#228]
Multiple files are not writable, this is just the tailend of a long list - is there a new permissions check App, I haven't had a problem before. 
**! /vendor/splitbrain/php-archive/src/Tar.php is not writable!
! /vendor/splitbrain/php-archive/src/Zip.php is not writable!
! /vendor/splitbrain/php-cli/README.md is not writable!
! /vendor/splitbrain/php-cli/src/Base.php is not writable!
! /vendor/splitbrain/php-cli/src/CLI.php is not writable!
! /vendor/splitbrain/php-cli/src/Colors.php is not writable!
! /vendor/splitbrain/php-cli/src/PSR3CLI.php is not writable!
! /vendor/splitbrain/php-cli/src/PSR3CLIv3.php is not writable!
! /vendor/splitbrain/php-jsstrip is not writable!**
 /vendor/splitbrain/php-jsstrip/LICENSE will be updated.
 /vendor/splitbrain/php-jsstrip/README.md will be updated.
 /vendor/splitbrain/php-jsstrip/src/Exception.php will be updated.
 /vendor/splitbrain/php-jsstrip/src/JSStrip.php will be updated.
! Some files aren't writable. Automatic upgrade not possible.

Errors above! You should not continue!

**Comment by splitbrain** [comment]
There is no change in how permissions are checked.
