### ISSUE TITLE
Error access git

### ISSUE THREAD

**Issue by MathieuCJ** [splitbrain/dokuwiki-plugin-upgrade#237]
I installed the upgrade plugin, but it require an internet connection to get the recent release (Cannot determine which is the most recent version) . 

In my case, I can't have this connection between my server and the git. 
But I have the Release package on my server. 

Is it possible to do this upgrade without access to the git ?

**Comment by splitbrain** [comment]
do a manual upgrade then. the upgrade plugin requires an internet connection
