### ISSUE TITLE
Upgrade plugin install messed with entire site

### ISSUE THREAD

**Issue by rjsdotorg** [splitbrain/dokuwiki-plugin-upgrade#238]
I added **Upgrade plugin** as per https://www.dokuwiki.org/plugin:extension
The entire site immediately lost it's style or something: https://travcopedia.com/doku.php

> DokuWiki 2023-04-04a "Jack Jackrum" is available for download.
> You're currently running DokuWiki 2020-07-29 "Hogfather".

I upgraded via **DokuWiki Upgrade Plugin** and the styling "came back".

**Comment by splitbrain** [comment]
closing this since no actionable info is provided.
