### ISSUE TITLE
Nothing besides Downloading archive from https://github.com/splitbrain/dokuwiki/archive/stable.tar.gz...

### ISSUE THREAD

**Issue by rvanlieshout** [splitbrain/dokuwiki-plugin-upgrade#42]
The download page only displays 'Downloading archive from https://github.com/splitbrain/dokuwiki/archive/stable.tar.gz...'  after a long period of time when trying to upgrade to Hrun.

After pressing continue on the check page it loads for several seconds (> 60) and presents me only the Downloading archive line.

The logs show:

    37.153.243.146 - - [02/Oct/2014:08:12:35 +0200] "GET /start?do=admin&page=upgrade&sectok=9fe5a30c4a2153453fdf1f8f0e10f5fd&step%5Bdownload%5D=Continue+%E2%9E%A1 HTTP/1.1" 200 2716 "http://<hostname>/start?do=admin&page=upgrade&sectok=9fe5a30c4a2153453fdf1f8f0e10f5fd&step%5Bversion%5D=Continue+%E2%9E%A1" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.1.17 (KHTML, like Gecko) Version/7.1 Safari/537.85.10"

**Comment by splitbrain** [comment]
I can not reproduce this and assume it to be fixed. Feel free to open a new ticket if you can give any useful additional info.
