### ISSUE TITLE
Seite "Check" bleibt leer

### ISSUE THREAD

**Issue by PitStorm** [splitbrain/dokuwiki-plugin-upgrade#51]
Bei Klick auf den Button "Continue" bleibt die Seite "Check" leer. Es wird nichts geladen und der Teil in dem Informationen stehen sollten bleibt leer.
![bug](https://cloud.githubusercontent.com/assets/9358125/4744966/2e061fbe-5a35-11e4-93d8-256cb6bd7c8f.JPG)

**Comment by splitbrain** [comment]
I can not reproduce this and assume it to be fixed. Feel free to open a new ticket if you can give any useful additional info.
