### ISSUE TITLE
Update messages don't want to disappear

### ISSUE THREAD

**Issue by p2or** [splitbrain/dokuwiki-plugin-upgrade#53]
Although the update works well and the wiki is up to date, dokuwiki displays all update messages like before.

![dokuwiki-update-messages](http://i.imgur.com/1bL4X2Z.png)

**Comment by borekb** [comment]
Probably the easier way for the Upgrader Plugin to fix this is to directly delete the `messages.txt` - touching config files should work, too, but it doesn't for me at the moment (it used to in the past).
