### ISSUE TITLE
update wiki plugin does not work behind proxy

### ISSUE THREAD

**Issue by ktp1976** [splitbrain/dokuwiki-plugin-upgrade#57]
update wiki plugin does not work behind proxy:

! Die neuste Version von DokuWiki konnte nicht ermittelt werden. Failed to establish secure proxy connection
! Die neuste Version von DokuWiki konnte nicht ermittelt werden.
Ihre DokuWiki-Version ist Release 2014-09-29b "Hrun"

Proxy settings:
Proxy-Server: 10.x.x.20
Proxy-Port: 3128
No Proxy username
No Proxy password
Proxy SSL: No

listing plugins (uses HTTP) works
installing plugins (uses HTTPS) does not work

so this seems more core related but it breaks funktionality of this plugin

php --version
PHP 5.3.10-1ubuntu3.15 with Suhosin-Patch (cli) (built: Oct 29 2014 12:19:04) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
    with XCache v1.3.2, Copyright (c) 2005-2011, by mOo

OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.0.1 14 Mar 2012
OpenSSL Header Version => OpenSSL 1.0.1 14 Mar 2012

**Comment by destroyica** [comment]
Hi, I have the same problem. Have you found a solution?

**Comment by okelet** [comment]
+1, same problem

**Comment by angystardust** [comment]
same problem here :'(

**Comment by Drachenlaeufer** [comment]
And to push this thread ... here too. :-(
Actually I had this problem before and found a solution somewhere ... I cannot find it again, but it had something to do with HTTPClient.php.
Any ideas?

**Comment by splitbrain** [comment]
should be fixed in newer dokuwiki releases
