### ISSUE TITLE
"Unpacking archive" hangs

### ISSUE THREAD

**Issue by 2xaronl** [splitbrain/dokuwiki-plugin-upgrade#58]
I've got Dokuwiki running on Kubuntu 14.10 and have installed the upgrade plugin.  When I attempt to upgrade from Hrun 2014-09-29a to Hrun 2014-09-29b I am able to proceed successfully until I get to the "Unpacking Archive" step.

I've poked around in the VerboseTarLib.class.php and it looks like the script begins reading the archive, finds the pax_global_header file and then hangs when attempting to perform the @gzseek in the skipbytes($bytes) function.

**Comment by thoni56** [comment]
Ditto.

**Comment by splitbrain** [comment]
most probably a bug in Ubuntu's PHP. see https://github.com/splitbrain/dokuwiki/issues/865

**Comment by splitbrain** [comment]
see also #44

**Comment by thoni56** [comment]
Thanks, I'll see if any of those fixes the issue here.

**Comment by thoni56** [comment]
Yes. The fix in #44 (https://github.com/splitbrain/dokuwiki/commit/8457f8cee42b57b7f708f23cbbfc50b1939de30d) fixed the issue for me. The fix does not seem to be released yet (46.2) ?

**Comment by thoni56** [comment]
Wasn't in 2014-09-29d "Hrun", either...
