### ISSUE TITLE
Startseite bleibt leer

### ISSUE THREAD

**Issue by Phoeniix** [splitbrain/dokuwiki-plugin-upgrade#62]
Nach dem Drücken auf "Continue" im ersten Screen des Plugins bleibt die nachfolgende Seite mit Schritt 1 einfach leer. Mehrere re-installs hatten keine Auswirkung. Cache der Wiki auch bereits bereinigt.

**Comment by splitbrain** [comment]
see http://doku.wiki/blankpage
