### ISSUE TITLE
way to exclude files from migration (png files for example)

### ISSUE THREAD

**Issue by dvasseur** [splitbrain/dokuwiki-plugin-upgrade#66]
For some reasons i had the chmod -w some media files (/lib/tpl/dokuwiki/images/logo.png) to prevent new dokuwiki versions to overwrite it. The plugin is detecting it (great!) but there is no option to bypass this and thus I cannot use the plugin to upgrade my wiki :(

**Comment by splitbrain** [comment]
You should not need to overwrite that logo. Refer to the documentation of your template on how to correctly set a custom logo.

**Comment by dvasseur** [comment]
I'm using "ACL/deny to all" for my whole wiki and there is no other way - at least I'm aware of - to display my logo on the authentication page
