### ISSUE TITLE
"Only variables should be passed..." error message on all pages of upgrade process

### ISSUE THREAD

**Issue by RSchwoerer** [splitbrain/dokuwiki-plugin-upgrade#69]
I get the following error on all pages of the upgrade process (see image below).

    Strict Standards: Only variables should be passed by reference in D:\home\site\wwwroot\lib\plugins\upgrade\admin.php on line 130

I confirmed I have the latest version installed. My 'admin.php' matches the current master.

![image](https://cloud.githubusercontent.com/assets/5709991/7187820/024bfdd8-e439-11e4-80bc-bfde0739815d.png)

**Comment by splitbrain** [comment]
DokuWiki usually supresses strict warnings. Have you tweaked your dokuwiki in that regard?

**Comment by splitbrain** [comment]
Also, are you using the most recent version of the plugin? line 130 seems not to be right.

**Comment by RSchwoerer** [comment]
I re-confirmed I'm running the latest version of the plugin.
And I don't think I've tweaked the PHP settings. 

I have the wiki deployed on Azure, not certain if that affects it.
I did try adding the php configuration to ignore strict standards (in the php.ini/user.ini file), but I cannot get that to work.

Do you know where dokuwiki is setting to supress those errors?

**Comment by splitbrain** [comment]
inc/init.php

**Comment by splitbrain** [comment]
Is this still an issue? I need a current line number at least to get an idea where the problem is.

**Comment by splitbrain** [comment]
no feedback given. assumed to be fixed
