### ISSUE TITLE
Update messages don't want to disappear

### ISSUE THREAD

**Issue by LordOfDragons** [splitbrain/dokuwiki-plugin-upgrade#74]
As the title says. With latest upgrade the message do not vanish no matter if waiting a day, deleting the cache messages.txt file or touching all configuration files. Seems to be a notorious bug and now turned into not removing messages at all. Half the page is full of these messages never going away for ever.

**Comment by Klap-in** [comment]
Due to improvements in DokuWiki itself, the update messages should disappear automatically, in the newest release of DokuWiki.
