### ISSUE TITLE
replace _rdel() by DokuWiki's io_rmdir()

### ISSUE THREAD

**Issue by Klap-in** [splitbrain/dokuwiki-plugin-upgrade#77]
function _rdel($dir) 
https://github.com/splitbrain/dokuwiki-plugin-upgrade/blob/master/admin.php#L202

How long backward compatible is this plugin?

**Comment by splitbrain** [comment]
Well it was tested from lemming onwards... I'd like to keep it as decoupled from the core as possible. It's not much code so I'd say I keep this implementation.
