### ISSUE TITLE
not compatible with 2015-08-10 "Detritus"

### ISSUE THREAD

**Issue by realdreams** [splitbrain/dokuwiki-plugin-upgrade#81]
after upgrading the version number is still Release 2014-09-29d "Hrun" and upgrade notification for 2015-08-10 "Detritus" won't go away

**Comment by splitbrain** [comment]
Then the upgrade did not go through. I just tried it with one of my wikis and it worked flawless

**Comment by realdreams** [comment]
I tried again and it worked this time. Not sure what happened last time. It said upgrade completed without error.
