### ISSUE TITLE
Should the verify doesn't turn out well

### ISSUE THREAD

**Issue by tormec** [splitbrain/dokuwiki-plugin-upgrade#85]
![verify](https://cloud.githubusercontent.com/assets/10964663/9462362/9a694d3a-4b15-11e5-8e30-747deb0ebb67.png)

If the verify step doesn't turn out well, maybe it would be better to not highlight the install step or show a "✘" instead of a "✔".

**Comment by splitbrain** [comment]
not worth the effort. won't implement
