### ISSUE TITLE
Upgrade plugin does not consider installed languages

### ISSUE THREAD

**Issue by fthommen** [splitbrain/dokuwiki-plugin-upgrade#89]
The upgrade plugin seems to install all languages, no matter which languages has been installed in the original installation.  Instead, it should only upgrade those languages which have in fact been installed previously and not ignore the original installers decision.

This might be similar to issue #55 (Choosing Languages) but it has an other perspective :-)

**Comment by splitbrain** [comment]
closing in favor of #55
