### ISSUE TITLE
No download link for use with Plugin Manager

### ISSUE THREAD

**Issue by Lookslikerain75** [splitbrain/dokuwiki-plugin-upgrade#93]
I can't find a link to download this using the download and install new plugin option, I can't install manually as I have dokuwiki built into a NAS so has to use the Plugin Management. Can you send me the correct link please.

**Comment by splitbrain** [comment]
The link is behind the download button on the plugin page.

**Comment by Lookslikerain75** [comment]
OK but downloads if you click that button but entering the url from the
button into the plugin download fails seems not to link to a zip file just
a folder.

**Comment by splitbrain** [comment]
It links to https://github.com/splitbrain/dokuwiki-plugin-upgrade/zipball/master which generates a zip file
